import { Book } from "@/types";

export const booksData: Book[] = [
  {
    id: "1",
    title: "Biologi Kelas X",
    author: "Kemdikbud",
    category: "Education",
    coverColor: "10b981",
    textColor: "ffffff",
    pages: 245,
    language: "Indonesia",
    rating: 4.5,
    desc: "Buku panduan lengkap Biologi untuk siswa kelas X SMA. Menjelaskan konsep biologi dari tingkat seluler hingga ekosistem besar dengan ilustrasi mendetail.",
  },
  {
    id: "2",
    title: "Laskar Pelangi",
    author: "Andrea Hirata",
    category: "Fiction",
    coverColor: "3b82f6",
    textColor: "ffffff",
    pages: 529,
    language: "Indonesia",
    rating: 4.8,
    desc: "Kisah inspiratif tentang sepuluh anak dari keluarga miskin di Pulau Belitung yang berjuang mempertahankan sekolah mereka di tengah berbagai keterbatasan dan kemiskinan.",
  },
  {
    id: "3",
    title: "Sains & Galaksi",
    author: "Pusat Sains",
    category: "Science & Technology",
    coverColor: "0f172a",
    textColor: "ffffff",
    pages: 128,
    language: "Indonesia",
    rating: 4.7,
    desc: "Panduan visual yang memukau tentang alam semesta, tata surya, bintang-bintang, dan galaksi. Cocok untuk semua umur guna menambah wawasan mengenai luasnya ciptaan alam semesta yang mengelilingi tempat tinggal kita.",
  },
  {
    id: "4",
    title: "Bumi Manusia",
    author: "Pramoedya A. T.",
    category: "Fiction",
    coverColor: "b45309",
    textColor: "ffffff",
    pages: 535,
    language: "Indonesia",
    rating: 4.8,
    desc: "Buku pertama dari Tetralogi Buru. Mengisahkan perjalanan Minke, seorang pribumi cerdas di era kolonial Belanda, berjuang menemukan jati diri dan menyuarakan kemerdekaan bangsanya melalui tulisan dan pergerakan.",
  },
  {
    id: "5",
    title: "Pemrograman Web",
    author: "Tim Developer",
    category: "Science & Technology",
    coverColor: "ef4444",
    textColor: "ffffff",
    pages: 180,
    language: "Indonesia",
    rating: 4.6,
    desc: "Buku latihan dan pendalaman materi mengenai dasar-dasar pemrograman web. Mengulas HTML, CSS, Javascript secara interaktif dan studi kasus pembuatan website yang responsif dan modern dari awal hingga proses rilis.",
  },
  {
    id: "6",
    title: "Fisika Kuantum",
    author: "Prof. Yohanes",
    category: "Scientific Works",
    coverColor: "8b5cf6",
    textColor: "ffffff",
    pages: 320,
    language: "Indonesia",
    rating: 4.3,
    desc: "Pengantar mudah dipahami mengenai konsep dasar mekanika kuantum dan aplikasinya pada dunia nyata. Menjawab rasa penasaran terkait perilaku partikel di tingkat atom dan implikasinya pada perkembangan teknologi masadepan.",
  },
  {
    id: "7",
    title: "Jurnal Pendidikan",
    author: "Ahli Sejarah",
    category: "Reference",
    coverColor: "d97706",
    textColor: "ffffff",
    pages: 410,
    language: "Indonesia",
    rating: 4.4,
    desc: "Kompilasi artikel dan riset terbaru mengenai perkembangan metode pendidikan modern, adaptasi teknologi di ruang kelas, dan hasil studi tentang efektivitas metode pembelajaran kolaboratif pada anak usia remaja di Indonesia.",
  },
];
